/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu May 03 02:00:48 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelos.com.ipn.mx.modelo;

public class EventoKey implements java.io.Serializable, Cloneable {
    /* idEvento */
    protected int idevento;

    /* idEvento */
    public int getIdevento() {
        return idevento;
    }

    /* idEvento */
    public void setIdevento(int idevento) {
        this.idevento = idevento;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idevento).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof EventoKey))
            return false;

        EventoKey key = (EventoKey) obj;

        if (this.idevento != key.idevento)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        EventoKey key = new EventoKey();
        key.idevento = this.idevento;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idevento").append(" = ").append(idevento).append("]");
        return sb.toString();
    }
}