/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Thu May 03 02:00:48 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package modelos.com.ipn.mx.modelo;

/*
 * For Table Evento
 */
public class Evento implements java.io.Serializable, Cloneable {
    private EventoKey _key = new EventoKey();

    /* idEvento, PK */
    protected int idevento;

    /* nombreEvento */
    protected String nombreevento;

    /* fechaEvento */
    protected java.util.Date fechaevento;

    /* duracionEvento */
    protected int duracionevento;

    /* fotoEvento */
    protected String fotoevento;

    /* Return the key object. */
    public EventoKey getKeyObject() {
        return _key;
    }

    /* idEvento, PK */
    public int getIdevento() {
        return idevento;
    }

    /* idEvento, PK */
    public void setIdevento(int idevento) {
        this.idevento = idevento;
        _key.setIdevento(idevento);
    }

    /* nombreEvento */
    public String getNombreevento() {
        return nombreevento;
    }

    /* nombreEvento */
    public void setNombreevento(String nombreevento) {
        this.nombreevento = nombreevento;
    }

    /* fechaEvento */
    public java.util.Date getFechaevento() {
        return fechaevento;
    }

    /* fechaEvento */
    public void setFechaevento(java.util.Date fechaevento) {
        this.fechaevento = fechaevento;
    }

    /* duracionEvento */
    public int getDuracionevento() {
        return duracionevento;
    }

    /* duracionEvento */
    public void setDuracionevento(int duracionevento) {
        this.duracionevento = duracionevento;
    }

    /* fotoEvento */
    public String getFotoevento() {
        return fotoevento;
    }

    /* fotoEvento */
    public void setFotoevento(String fotoevento) {
        this.fotoevento = fotoevento;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Evento))
            return false;

        Evento bean = (Evento) obj;

        if (this.idevento != bean.idevento)
            return false;

        if (this.nombreevento == null) {
            if (bean.nombreevento != null)
                return false;
        }
        else if (!this.nombreevento.equals(bean.nombreevento)) 
            return false;

        if (this.fechaevento == null) {
            if (bean.fechaevento != null)
                return false;
        }
        else if (!this.fechaevento.equals(bean.fechaevento)) 
            return false;

        if (this.duracionevento != bean.duracionevento)
            return false;

        if (this.fotoevento == null) {
            if (bean.fotoevento != null)
                return false;
        }
        else if (!this.fotoevento.equals(bean.fotoevento)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Evento bean = new Evento();
        bean.idevento = this.idevento;
        bean.nombreevento = this.nombreevento;
        if (this.fechaevento != null)
            bean.fechaevento = (java.util.Date) this.fechaevento.clone();
        bean.duracionevento = this.duracionevento;
        bean.fotoevento = this.fotoevento;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idevento").append(" = ").append(idevento).append("]").append(sep);
        sb.append("[").append("nombreevento").append(" = ").append(nombreevento).append("]").append(sep);
        sb.append("[").append("fechaevento").append(" = ").append(fechaevento).append("]").append(sep);
        sb.append("[").append("duracionevento").append(" = ").append(duracionevento).append("]").append(sep);
        sb.append("[").append("fotoevento").append(" = ").append(fotoevento).append("]").append(sep);
        return sb.toString();
    }
}